version: '3.9'

services:
  olama:
    image: ollama/ollama:latest
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_app
    depends_on:
      - olama
    environment:
      - OLLAMA_URL=http://olama:11434
    ports:
      - "8501:8501"

volumes:
  ollama:
