version: '3.9'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu] # Para suporte a GPU, se necessário.

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_app
    ports:
      - "8501:8501"
    depends_on:
      - ollama

volumes:
  ollama:
